M48
; DRILL file {KiCad (6.0.4)} date Tue 02 Aug 2022 08:21:40 AM CEST
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2022-08-02T08:21:40+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X19050Y-19050
X19050Y-68580
X96520Y-19050
X96520Y-68580
T0
M30
